# Generated by Django 5.2.2 on 2025-06-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('islem_id', models.AutoField(primary_key=True, serialize=False)),
                ('islem_tarihi', models.DateTimeField()),
                ('islem_turu', models.CharField(choices=[('gelir', 'Gelir'), ('gider', 'Gider')], max_length=10)),
                ('islem_miktari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yapan_kisi', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
            ],
        ),
    ]
