# Generated by Django 5.2.2 on 2025-06-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islemler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-islem_tarihi'], 'verbose_name': 'İşlem', 'verbose_name_plural': 'İşlemler'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='aciklama',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='islem_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='İşlem ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='islem_miktari',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='İşlem Miktarı'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='islem_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='islem_turu',
            field=models.CharField(choices=[('gelir', 'Gelir'), ('gider', 'Gider')], max_length=10, verbose_name='İşlem Türü'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='yapan_kisi',
            field=models.CharField(max_length=100, verbose_name='Yapan Kişi'),
        ),
    ]
